version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis:7

volumes:
  postgres_data:
