test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  endpoint: <%= ENV['DO_SPACES_ENDPOINT'] %>
  access_key_id: <%= ENV['DO_SPACES_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['DO_SPACES_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['DO_SPACES_BUCKET'] %>
  region: <%= ENV['DO_SPACES_REGION'] %>
